# domain: JFurber.github.io
# url: https://JFurber.github.io
# baseurl: /Maths-PGR-Conference-2023/
theme: jekyll-theme-cayman
title: Understanding the Fine Movements of Badgers
description: Jessica Furber

